//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cropdistributioncenter
    {
        public int CropID { get; set; }
        public string Cropname { get; set; }
        public string Cropquantity { get; set; }
        public string Croprate { get; set; }
        public string Address { get; set; }
    }
}
