//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UserdataEntities : DbContext
    {
        public UserdataEntities()
            : base("name=UserdataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cropdistributioncenter> Cropdistributioncenters { get; set; }
        public virtual DbSet<Soiltypetable> Soiltypetables { get; set; }
        public virtual DbSet<Usertable> Usertables { get; set; }
        public virtual DbSet<Admintable> Admintables { get; set; }
    }
}
