//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Soiltypetable
    {
        public int SoilID { get; set; }

        [Required(ErrorMessage = "SoliType is required")]
       public string SoilType { get; set; }

        
        [Required(ErrorMessage = "Crop names is required")]
        [DisplayName("Crop names")]
        public string Process1 { get; set; }

      
        [DisplayName("Addtional Crop details")]
        public string Process2 { get; set; }
    }
}
