//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Customer_portal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Usertable
    {
        public int UserID { get; set; }

        [Required(ErrorMessage = "User name is required")]
        [DisplayName("User Name")]
        [MaxLength(12)]
        public string EmailAddress { get; set; }
        
        [Required(ErrorMessage = "Password is required")]
        [DataType(DataType.Password)]
        
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "The Password and Confirmation password do not match")]
        public string ConfirmPassword { get; set; }

        
        [DisplayName("Serial Number")]
        public string PhoneNumber { get; set; }

    }

}
